### ISSUE TITLE
Give points for small subtasks

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#199]
This way, even though the complete skill is not achieved, some points can still be scored.

This does require extensive score sheets. 

Some subtasks:
- [ ] speech recognition (Single word) 
- [ ] Grabbing any item
- [ ] Correctly recognizing an item as the item _not_ searched for
- [ ] ...

**Comment by LoyVanBeek** [comment]
For this, we have human referees.
