### ISSUE TITLE
Draft Restructured Tasks

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#488]
This issue is to track the restructured tasks being drafted. Finishing touches will be tracked with #489.
The Rule-book is being restructured in the branch **2019/restructure**

Scenarios:
1. House Holder (aka Chores, manipulation)
- [x] Clean the Table (5 objects to dishwasher)
  - [ ] Scoresheet
- [x] Storing Groceries #490
  - [ ] Scoresheet
- [x] Setting Table (5 objects from cupboard to table) #491
  - [ ] Scoresheet
- [x] Clean up (Find 5 scattered objects in room, move them to predefined locations) #492 
  - [ ] Scoresheet
- [ ] Take out garbage #493
  - [ ] Scoresheet

2. Party Host (aka buttler/waiter, HRI)
- [x] Serving Drinks #494 
  - [ ] Scoresheet
- [x] Receptionist (Open door, guide to living room, introduce guests) #495 
  - [ ] Scoresheet
- [x] Farewell (give coat and guide to cab) #496 
  - [ ] Scoresheet
- [ ] Restaurant (Update to make it goal-compliant) #497 
  - [ ] Scoresheet
- [ ] Cocktail Party (Stage II, merge Receptionist & Serving Drinks. Rise complexity) --No issue--
  - [ ] Scoresheet

**Comment by moriarty** [comment]
I can assign 10 people in GitHub, but not all the members of the TC are assignable.

https://github.com/RoboCupAtHome/RuleBook/blob/3664368d805d2c93fcf47ea6e76d20e618731e9f/introduction/Organization.tex#L23-L31

@RoboCupAtHome/technical-commmittee 
@johaq @oscar-lima

I don't know the GitHub usernames for Agnes Delaborde, Allison Henry, Marta Angelica Nakayama and Yutaro Ishida

**Comment by kyordhel** [comment]
Well, first thing about beint a TC member is being interested in being a TC
member.

People knew that discussion would be held in GitHub. If they haven’t
requested to join, they haven’t been present in the discussions, etc.,
that’s a clear sign they quit their charge. To me, a person who didn’t
participate in rule crafting cannot have TC privileges during competition.
Merits over democracy is my saying.

Still, you can be Mr. Nice Guy and send them an email reminding them their
decition/duties. Is up to you.

**Comment by moriarty** [comment]
The state (on Nov 4 at 14:29) of @kyordhel 's branch has one example task already drafted.
The task nearly fits on one page, and is clear and understandable. So will copy it and change it to GitHub Mark Down here for quick reference.

RoboCup@Home Rulebook / Draft version for RoboCup 2019 (Revision 2018-11-04 833)Chapter 6. Tests in Stage II

# Scenario: Household Chore
## Task: Clean the Table
The robot has to remove all dishes from a table (presumably after dinner) and place them into
the dishwasher.
### Main Goal
All the tableware and cutlery is inside the dishwasher.
Reward: 1000pts
### Bonus rewads
1. Opening the dishwasher door (300pts)
2. Pulling out the dishwasher racks (300pts)
3. Placing the Cascade Pod inside the dishwasher (300pts)
4. Leaving the arena (100pts)
### Setup
* Location: This test takes place in the arena. A dining table is located close to the
dishwasher.
* Tray: A plastic tray is located either on top of the dishwasher, or onto one of its racks.
The tray may have tableware and cutlery placed inside already.
* Table setting: The table has a total of 6 objects disposed in a typical setting for a meal
for one person Distribution is as follows:
  * Silverware: Any two objects (fork, knife, spoon).
  * Tableware: Any three objects, excluding silverware. At least one must be a dish.
  * Cascade Pod : One Cascade Pod.
### Additional rules and remarks
1. Safe placing: Objects must be placed with care. It must be clear that the robot is trying
to place the object, not throwing or dropping it.
2. Dishwasher: The team decides whether the robot will place the objects in the dish-
washer’s rack or in the official tray.
3. Dishwasher door: The dishwasher door is open and with the racks pulled out by default.
The team leader can, however, request the diswasher to be closed and score additional
points for opening it. If the robot fails to open the door, it must clearly state it and
request the referee to open it.
### Referee instructions
The referee needs to
* Place the table setting.
* Place the tray on the dishwasher or onto the rack, as requested by the team.
### OC instructions
1. During Setup days:
  * Provide official cutlery and tableware for training.
2. hours before the test:
  * Announce the predefined location to take the command.
  * Announce the predefined location of the Cascade Pod.

**Comment by awesomebytes** [comment]
Hello, we propose for Stage I another test called [**Find my mates**](https://github.com/RoboCupAtHome/RuleBook/issues/499) from the Party Host scenario. There is further description and reasoning in the issue. If it is believed it fits, could you add it to the list on your post @moriarty ?

**Comment by ARTenshi** [comment]
Hello,

may I suggest to add a condition for the restarts? Before each slot, the referees should have a pool of randomly-selected objects to be used in a given task and then choose some of them depending on the test conditions. After a restart, the referees are allowed to change the position of the current objects in the arena and/or replace any object for a new one from the pool. 

This is to avoid any hard-coding during the restarting time (very easily a team can navigate to a table, ask for a restart, very fast tag the objects in front of the robot and then continue the task).

Regards,
Luis

**Comment by kyordhel** [comment]
No to both of you. We don’t want constant difficulty in tests but
equivalent. So yea, objects and placements WILL change between runs and
tests as they have always will. I can exchange an apple with an orange, and
swap it with a coke. Robots MUST deal with this incertitude.

As of the restart. There is no time for that. We have a line of teams and
teams can solve any task they want in their 5 minutes. If they fail to
start, they drop the test and can line up in the next round. OC will
schedule at least two, but we will have as many rounds as the time allows
it.  The more teams fail, the more tries they get.

**Comment by ARTenshi** [comment]
Understood. As long as it has already been discussed and discarded, I am happy with it. 

Regards,
Luis

PS. About time consumption -- just to clarify, although it will not be considered anymore --, provided that a referee already has one or two extra objects in her/his hand, it should take no more than a couple of seconds to move one object already in the arena or replace one with another whenever s/he considers it pertinent, while the team moves their robot to the restarting point (preserving equivalent difficulty).

**Comment by kyordhel** [comment]
Bump
