### ISSUE TITLE
TC TODO list 2024

### ISSUE THREAD

**Issue by PetervDooren** [RoboCupAtHome/RuleBook#809]
- [x] Briefer rulebook #803 
- [x] Teams should score #804 
- [ ] More open world (exit statemachine solutions) #805 
- [ ] Scoring mandates solving the challenge #806 
- [ ] Partial scoring? #808 
- [x] GPSR command generation #807
- [ ] increase scientific output
